In [ ]:
#assigement 2 feb

In [4]:
#question number 1

In [6]:
#The for loop is used when we already know the number of iterations, which means when we know how many times a statement has to be executed. 
#That is why we have to specify the ending point in the for loop initialization. 
#When we need to end the loop on a condition other than the number of times, we use a while loop"

In [7]:
#question number 2

In [29]:
# Sum of natural numbers up to num

num = 10

if num < 0:
    print("Enter a positive number")
else:
    sum = 0
   # use while loop to iterate until zero
while(num > 0):
             sum += num
             num -= 1
             print("The sum is",sum)

The sum is 10
The sum is 19
The sum is 27
The sum is 34
The sum is 40
The sum is 45
The sum is 49
The sum is 52
The sum is 54
The sum is 55

In [30]:
# question number 3

In [31]:
unit = int(input("Enter your unit: "))
if unit <= 100:
    bill = unit * 4.5
elif unit >= 101 and unit <= 200:
    bill = 346 + ((unit - 100) * 6)
elif unit >= 201 and unit <= 300:
    bill = 346 + 1486 + ((unit - 300) * 10)
else:
    bill = 346 + 1486 + 2064 + ((unit - 500) * 20)
print("Bill Per Unit:",bill)
bill = bill + (unit*1.45)
print("Bill after adding Line rent:",bill)
bill = bill + 100
print("Bill after adding Meter rent:",bill)
bill = bill + (bill*0.16)
print("Total Bill after adding tax:",bill)

Enter your unit:  310

Bill Per Unit: 96
Bill after adding Line rent: 545.5
Bill after adding Meter rent: 645.5
Total Bill after adding tax: 748.78

In [32]:
#question number 4

In [39]:
i=100
l=[]
for i in range(0,100):
    print(i**3)
    if i%4==0 and i%5==0:
        l.append(i)
    else:
        print("not divisible by 4 and 5")

0
1
not divisible by 4 and 5
8
not divisible by 4 and 5
27
not divisible by 4 and 5
64
not divisible by 4 and 5
125
not divisible by 4 and 5
216
not divisible by 4 and 5
343
not divisible by 4 and 5
512
not divisible by 4 and 5
729
not divisible by 4 and 5
1000
not divisible by 4 and 5
1331
not divisible by 4 and 5
1728
not divisible by 4 and 5
2197
not divisible by 4 and 5
2744
not divisible by 4 and 5
3375
not divisible by 4 and 5
4096
not divisible by 4 and 5
4913
not divisible by 4 and 5
5832
not divisible by 4 and 5
6859
not divisible by 4 and 5
8000
9261
not divisible by 4 and 5
10648
not divisible by 4 and 5
12167
not divisible by 4 and 5
13824
not divisible by 4 and 5
15625
not divisible by 4 and 5
17576
not divisible by 4 and 5
19683
not divisible by 4 and 5
21952
not divisible by 4 and 5
24389
not divisible by 4 and 5
27000
not divisible by 4 and 5
29791
not divisible by 4 and 5
32768
not divisible by 4 and 5
35937
not divisible by 4 and 5
39304
not divisible by 4 and 5
42875
not divisible by 4 and 5
46656
not divisible by 4 and 5
50653
not divisible by 4 and 5
54872
not divisible by 4 and 5
59319
not divisible by 4 and 5
64000
68921
not divisible by 4 and 5
74088
not divisible by 4 and 5
79507
not divisible by 4 and 5
85184
not divisible by 4 and 5
91125
not divisible by 4 and 5
97336
not divisible by 4 and 5
103823
not divisible by 4 and 5
110592
not divisible by 4 and 5
117649
not divisible by 4 and 5
125000
not divisible by 4 and 5
132651
not divisible by 4 and 5
140608
not divisible by 4 and 5
148877
not divisible by 4 and 5
157464
not divisible by 4 and 5
166375
not divisible by 4 and 5
175616
not divisible by 4 and 5
185193
not divisible by 4 and 5
195112
not divisible by 4 and 5
205379
not divisible by 4 and 5
216000
226981
not divisible by 4 and 5
238328
not divisible by 4 and 5
250047
not divisible by 4 and 5
262144
not divisible by 4 and 5
274625
not divisible by 4 and 5
287496
not divisible by 4 and 5
300763
not divisible by 4 and 5
314432
not divisible by 4 and 5
328509
not divisible by 4 and 5
343000
not divisible by 4 and 5
357911
not divisible by 4 and 5
373248
not divisible by 4 and 5
389017
not divisible by 4 and 5
405224
not divisible by 4 and 5
421875
not divisible by 4 and 5
438976
not divisible by 4 and 5
456533
not divisible by 4 and 5
474552
not divisible by 4 and 5
493039
not divisible by 4 and 5
512000
531441
not divisible by 4 and 5
551368
not divisible by 4 and 5
571787
not divisible by 4 and 5
592704
not divisible by 4 and 5
614125
not divisible by 4 and 5
636056
not divisible by 4 and 5
658503
not divisible by 4 and 5
681472
not divisible by 4 and 5
704969
not divisible by 4 and 5
729000
not divisible by 4 and 5
753571
not divisible by 4 and 5
778688
not divisible by 4 and 5
804357
not divisible by 4 and 5
830584
not divisible by 4 and 5
857375
not divisible by 4 and 5
884736
not divisible by 4 and 5
912673
not divisible by 4 and 5
941192
not divisible by 4 and 5
970299
not divisible by 4 and 5

In [40]:
#Question number 5

In [48]:


# Program to count the number of each vowels

# string of vowels
vowels = 'aeiou'

ip_str = " I want to be  datascients"

# make it suitable for caseless comparisions
ip_str = ip_str.casefold()

# make a dictionary with each vowel a key and value 0
count = {}.fromkeys(vowels,0)

# count the vowels
for char in ip_str:
   if char in count:
       count[char]+=11

print(count)

{'a': 33, 'e': 22, 'i': 22, 'o': 11, 'u': 0}